### ISSUE TITLE
Failed sampling can result in valid arm configuration

### ISSUE THREAD

**Issue by jeking04** [personalrobotics/or_ompl#17]
Currently, if failing to sample a goal from TSRGoal, the retuned configuration is all 0s. This can be a valid configuration for some robots, resulting in a plan to an incorrect goal. Set the configuration to something outside joint limits if sampling failed.

**Comment by psigen** [comment]
Does it make more sense to return an invalid constant like a NaN or Double::MAX_VAL/POS_INFINITY?

**Comment by jeking04** [comment]
Yup, i think so. making the change and testing it out now.

**Comment by psigen** [comment]
Ok, I've heard some people make arguments against using those values because they can trigger exception chains if they are accidentally used in mathematical computations, which can cause massive slowdowns, but I think the benefit of having a clear test expression and invalid mathematical results are useful.

**Comment by jeking04** [comment]
Okay, have a look. I fixed it here: 1e4d5db2a5d32ef95c42829b6e89b102f2f86e52

**Comment by mkoval** [comment]
LGTM.
