### ISSUE TITLE
Build error ubuntu 14.04/indigo

### ISSUE THREAD

**Issue by athackst** [personalrobotics/or_ompl#26]
I get this error when I try to build

'''
/home/athackst/cmu/src/or_ompl/src/OMPLPlanner.cpp: In member function ‘ompl::base::PlannerPtr or_ompl::OMPLPlanner::CreatePlanner(const or_ompl::OMPLPlannerParameters&)’:
/home/athackst/cmu/src/or_ompl/src/OMPLPlanner.cpp:259:41: error: ‘const class TiXmlElement’ has no member named ‘ValueStr’
         std::string const key = it_ele->ValueStr();
                                         ^
make[2]: *** [or_ompl/CMakeFiles/or_ompl.dir/src/OMPLPlanner.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
'''

Is there a specific version of TinyXml (or branch) I should be using?  I have libtinyxml2.6.2

**Comment by mkoval** [comment]
I believe that is correct. TinyXML is a bit funny strange because libtinyxml-dev and libtinyxml2-dev are two completely separate packages. I believe or_ompl uses libtinyxml-dev, but I am not 100% sure because I have both installed on my machine.

The rosdep keys specified in the package.xml file are definitely correct, so you can also try using rosdep to install the dependencies.

**Comment by athackst** [comment]
Reinstalled things and I got everything to compile.  Yay!
