### ISSUE TITLE
getValidSegmentLength() returns 0 at planner factory constructor call

### ISSUE THREAD

**Issue by Shushman** [personalrobotics/or_ompl#34]
At the time my planner factory's constructor is called, it needs `space->getLongestValidSegmentLength()`, which returns 0. `space->getMaximumExtent()` also returns 0, while `space->getLongestValidSegmentFraction()` returns a non-zero value.

**Comment by cdellin** [comment]
Note that we're pretty sure that this is because the state space's `StateSpace::setup()` method is not called by `or_ompl`.  This does not affect many other OMPL planners because they use, for example, `tools::SelfConfig::configurePlannerRange()`, which uses `StateSpace::getMaximumExtent()`, which doesn't require `StateSpace::setup()` to be called.  In any case, after the planner is constructed, when the `SimpleSetup` object's `solve()` method is called, it will then call `StateSpace::setup()` ... but this is after the planner has been constructed.  I think the right thing to do is for `or_ompl` to call `StateSpace::setup()` once the state space has been fully configured, but before the planner is constructed.

**Comment by mkoval** [comment]
@cdellin Would it be appropriate to call `setup()` right before [this line](https://github.com/personalrobotics/or_ompl/blob/master/src/OMPLPlanner.cpp#L207):
```c++
m_planner = CreatePlanner(*m_parameters);
```

**Comment by cdellin** [comment]
@mkoval that would certainly fix this issue, but since nothing in `OMPLPlanner::InitPlan()` reconfigures anything in the state space after it is returned by `or_ompl::CreateStateSpace()`, I think it makes sense to call `setup()` either inside `or_ompl::CreateStateSpace()` before it returns, or just after.  (Note that it's safe to call `setup()` multiple times.)

**Comment by Shushman** [comment]
Uh..not to be the bearer of bad news, but I still get `space->getLongestValidSegmentLength() = 0` in my planner's constructor even after the new changes.
Or maybe I am doing something wrong..

**Comment by cdellin** [comment]
I can't reproduce this; it appears to work for me with the new `setup()` call.  I attached a minimal test case below (extract with `patch -p0 < ompl_setup_test.patch.txt`).  @Shushman, could you try this?  The output should be:

```
[OMPLConversions.cpp:173 CreateStateSpace] Robot specifies DOF weights. Only unit weights are supported by OMPL; planning will commence as if there are no weights.
space getValidSegmentLength(): 0.011796
[OMPLPlanner.cpp:237 CreatePlanner] Failed creating planner.[OMPLPlanner.cpp:211 InitPlan] Failed creating OMPL planner.
```

[ompl_setup_test.patch.txt](https://github.com/personalrobotics/or_ompl/files/32164/ompl_setup_test.patch.txt)

**Comment by mkoval** [comment]
@Shushman did you try @cdellin's test code? What's the result?

**Comment by Shushman** [comment]
Yeah I am able to get this result for the test patch. I'll go back to checking my main package.
